name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        shell: bash
        run: |
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          elif [ -f requirements.txt ]; then
            # Ensure test and client deps even if requirements.txt is minimal
            pip install -r requirements.txt httpx pytest
          else
            # Fallback: install essentials inline
            pip install fastapi uvicorn pydantic pytest httpx
          fi

      - name: Generate bench data (optional)
        run: |
          python - <<'PY'
          import json, pathlib, random
          p = pathlib.Path("uire/data"); p.mkdir(parents=True, exist_ok=True)
          with open(p/"uire_bench.jsonl", "w") as f:
              for i in range(20):
                  f.write(json.dumps({
                      "q": f"test query {i}",
                      "domain": random.choice(["search","recommend","translate"])
                  })+"\n")
          PY

      - name: Run tests
        run: pytest -q


      - name: Run tests
        run: pytest -q
